#!/bin/sh

getent group messagebus >/dev/null || addgroup -g 18 messagebus
getent passwd messagebus >/dev/null || adduser -g messagebus -s /bin/false messagebus

chown root:messagebus /usr/libexec/dbus-daemon-launch-helper
chmod 4750 /usr/libexec/dbus-daemon-launch-helper

dbus-uuidgen --ensure
