#!/bin/sh

getent group messagebus >/dev/null || addgroup -S messagebus 2>/dev/null
getent passwd messagebus >/dev/null || adduser -S -D -H -h /dev/null -s /sbin/nologin -G messagebus -g messagebus messagebus 2>/dev/null

chown root:messagebus /usr/libexec/dbus-daemon-launch-helper
chmod 4750 /usr/libexec/dbus-daemon-launch-helper

dbus-uuidgen --ensure
