#!/bin/sh
[ -f /etc/rc.conf ] && . /etc/rc.conf
if [ ! "$WIFI_DEV" ]; then
	for i in /sys/class/net/*; do
		[ -e $i/phy80211 ] && {
			WIFI_DEV=${i##*/}
			break
		}
	done
fi
[ "$WIFI_DEV" ] || exit 1
exec wpa_supplicant -D nl80211 -i $WIFI_DEV -c /etc/wpa_supplicant.conf 2>&1
